/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sage.ideatool.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the sageCategory service. Represents a row in the &quot;sage_sageCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sage.ideatool.model.impl.sageCategoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sage.ideatool.model.impl.sageCategoryImpl}.
 * </p>
 *
 * @author 009
 * @see sageCategory
 * @see com.sage.ideatool.model.impl.sageCategoryImpl
 * @see com.sage.ideatool.model.impl.sageCategoryModelImpl
 * @generated
 */
public interface sageCategoryModel extends BaseModel<sageCategory>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sage category model instance should use the {@link sageCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this sage category.
	 *
	 * @return the primary key of this sage category
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sage category.
	 *
	 * @param primaryKey the primary key of this sage category
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the category ID of this sage category.
	 *
	 * @return the category ID of this sage category
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this sage category.
	 *
	 * @param categoryId the category ID of this sage category
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the company ID of this sage category.
	 *
	 * @return the company ID of this sage category
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this sage category.
	 *
	 * @param companyId the company ID of this sage category
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this sage category.
	 *
	 * @return the group ID of this sage category
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this sage category.
	 *
	 * @param groupId the group ID of this sage category
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this sage category.
	 *
	 * @return the user ID of this sage category
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this sage category.
	 *
	 * @param userId the user ID of this sage category
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this sage category.
	 *
	 * @return the user uuid of this sage category
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this sage category.
	 *
	 * @param userUuid the user uuid of this sage category
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this sage category.
	 *
	 * @return the user name of this sage category
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this sage category.
	 *
	 * @param userName the user name of this sage category
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this sage category.
	 *
	 * @return the create date of this sage category
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this sage category.
	 *
	 * @param createDate the create date of this sage category
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this sage category.
	 *
	 * @return the modified date of this sage category
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this sage category.
	 *
	 * @param modifiedDate the modified date of this sage category
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this sage category.
	 *
	 * @return the title of this sage category
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this sage category.
	 *
	 * @param title the title of this sage category
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this sage category.
	 *
	 * @return the description of this sage category
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this sage category.
	 *
	 * @param description the description of this sage category
	 */
	public void setDescription(String description);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(sageCategory sageCategory);

	public int hashCode();

	public CacheModel<sageCategory> toCacheModel();

	public sageCategory toEscapedModel();

	public String toString();

	public String toXmlString();
}